[package]
authors = ["Without Boats <woboats@gmail.com>"]
name = "io-adapter"
version = "0.1.0"

[dependencies]
serde_json = { git = "https://github.com/withoutboats/json", branch = "serializeable_objects" }
